server:
  port: 9093

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/Users/**

        - id: HOTEL-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/hotel/**
#if we want to give the multiple URL have to give the comma and Give the One url example
        # /hotel/**,/staffs/**

        - id: RATING-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/rating/**.
  config:
    import: optional:configserver:http://localhost:9094



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



