


server:
  port: 9092
spring:
  config:
    import: optional:configserver:http://localhost:9094
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/microservice
  jpa:
    properties:
      hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

    hibernate:
      ddl-auto: update

    show-sql: true
  application:
    name: RATING-SERVICE


#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true
#server.port=9092


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true


    service-url:
      defaultZone: http://localhost:8761/eureka/



#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
